### ISSUE TITLE
How cloud I change icon color

### ISSUE THREAD

**Issue by rffanlab** [mazipan/vue-ionicons#12]
How cloud I change icon color

**Comment by rffanlab** [comment]
color set in your demo has been failed

**Comment by mazipan** [comment]
In my demo page, using inline style like this code: https://github.com/mazipan/vue-ionicons/blob/master/demo/App.vue#L51

But you can also using props `rootClass` then set CSS style based on those rootClass.

**Comment by floydback** [comment]
You should use css _fill_ property
```
.ion {
  fill: #fff;
}
```
