### ISSUE TITLE
How to import set of icons

### ISSUE THREAD

**Issue by floydback** [mazipan/vue-ionicons#13]
I want to import globally set of [ios-*] icons. Is it possible with 3 or 4 lines of code without copy/paste? I've see _/dist/ionicons.js_ file but don't understand how to use ioniconsPlugin im my VueJS App. Could anyone help me?

**Comment by mazipan** [comment]
Yes, it is plugin based.
You can use with

```
import Vue from 'vue'
import plugin from 'vue-ionicons/dist/ionicons.js'

Vue.use(plugin)
```

But for now, it will import all icons.
And I don't recommend this things.

Need to generate another files if you want specific set of icons.

Maybe we can generate like `ionicons-ios.js`.

**Comment by mazipan** [comment]
Done.
Read docs: https://github.com/mazipan/vue-ionicons#import-some-icon-sets
