### ISSUE TITLE
Is this project dead even the demo is not work?

### ISSUE THREAD

**Issue by seawenzhu** [mazipan/vue-ionicons#4]
Anyone konws?
there is bellow error when run demo
![image](https://user-images.githubusercontent.com/5305068/33007272-f09c5d32-ce08-11e7-9b10-e719cf13b2c9.png)

**Comment by mazipan** [comment]
Very sorry, for long ago not check this project.
Actually this project still under development and didn't recommended for using in production env.
If you have time, PR is very welcome.
